### ISSUE TITLE
Empty and abandoned...

### ISSUE THREAD

**Issue by wasdennnoch** [ZieIony/Stalker#1]
Did you just forget this repo or are you workin on something big? ^^

**Comment by ZieIony** [comment]
This project is much bigger than all other repos together. Carbon is the UI layer of it.

The reason this repo is empty is very simple - I don't have a credit card to pay for a private github repo. That's why I'm using another hosting for Stalker.

**Comment by wasdennnoch** [comment]
Oh ok then. Still, a note in the readme would stop some confusion ;)
Is it purely private or will you bublish it at some point? I mean, what else would this repo be for.

**Comment by ZieIony** [comment]
Stalker will be public at some point, but most likely I will keep the sources closed. I'm publishing useful parts of it as separate repos (DataAPI, FragmentManager, EventBus)

Nothing I guess. I'll remove it then. If you're curious, watch my blog. It's name may give you a hint about what Stalker is ;)

**Comment by wasdennnoch** [comment]
The repo description says analytics tool - yet another one :P
